<h2>Tout nos produits</h2>

<div class="article">
<?php foreach($selections as $select): ?>

    <article class="article-card">
        <h2><?= $select->getName(); ?></h2>
        <p>
            <?= $select->getDescription(); ?>
        </p>
        
        <p> 
            <?= $select->getPrice(); ?>$
        </p>
        <img src=" <?= $select->getImg();  ?> "></img>
        
        
        <a href="index.php?page=product&id=<?= $select->getId();  ?>" class="produit-unique">Voir plus !</a>
    </article>
    
<?php endforeach; ?>

</div>