<h2><?= $selectOne->getName() ?></h2>

<a href="index.php?page=products" class="return-home" >Revoir nos produits</a>

<div class="article">

    <article class="article-card">
    <img src=" <?= $selectOne->getImg()  ?> "></img>
        <p class="desc">
            <?= $selectOne->getDescription() ?>
        </p>
        
        <p class="price"> 
            <?= $selectOne->getPrice() ?>$
        </p>
        
        
    </article>
    

</div>